# Build and test a Java project using Apache Maven on Azure Pipelines.
trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  name: 'Default'   # Name of the agent pool
  demands:
  #- agent.name -equals omv6   # This will make sure the build runs only on omv6 agent


variables:
  # Use Azure DevOps environment variables for Sauce Labs credentials.
  sauce_user: $(SAUCE_USERNAME)
  sauce_key: $(SAUCE_ACCESS_KEY)

steps:
  # Display the environment variable names (not the values) for debugging purposes.
  - script: |
      echo "SAUCE_USER variable name is set."
      echo "SAUCE_KEY variable name is set."
    displayName: 'Check Environment Variables'

  # Build and test the Maven project.
  - task: Maven@3
    displayName: 'Maven Build and Test'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
