# Build and test a Java project using Apache Maven on Azure Pipelines.
trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  name: 'Default'   # Name of the agent pool
  #demands:
  #- agent.name -equals omv6   # This will make sure the build runs only on omv6 agent


variables:
  # Use Azure DevOps environment variables for Sauce Labs credentials.
  sauce_user: $(SAUCE_USERNAME)
  sauce_key: $(SAUCE_ACCESS_KEY)

steps:
  # Set the JAVA_HOME environment variable for this run.
  - script: |
      echo "Setting JAVA_HOME_11_X64 environment variable"
      echo "##vso[task.setvariable variable=JAVA_HOME_11_X64]/usr/lib/jvm/java-11-openjdk-amd64"
    displayName: 'Set JAVA_HOME_11_X64'

  # Display the environment variable names (not the values) for debugging purposes.
- script: |
    if [ -z "$SAUCE_USER" ]; then
      echo "SAUCE_USER is EMPTY!"
    else
      echo "SAUCE_USER is set."
    fi

    if [ -z "$SAUCE_KEY" ]; then
      echo "SAUCE_KEY is EMPTY!"
    else
      echo "SAUCE_KEY is set."
    fi
  displayName: 'Verify SAUCE_USER and SAUCE_KEY'


  - script: |
    echo "SAUCE_USER: $SAUCE_USER"
    echo "SAUCE_KEY: $SAUCE_KEY"
  displayName: 'Echo SAUCE_USER and SAUCE_KEY'



  # Build and test the Maven project.
  - task: Maven@3
    displayName: 'Maven Build and Test'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

