# Build and test a Java project using Apache Maven on Azure Pipelines.
trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

pool:
  name: 'Default'   # Name of the agent pool
  #demands:
  #- agent.name -equals omv6   # This will make sure the build runs only on omv6 agent

variables:
  # Use Azure DevOps environment variables for Sauce Labs credentials.
  sauce_user: $(SAUCE_USERNAME)
  sauce_key: $(SAUCE_ACCESS_KEY)
  docker_image_name: micktaylorse/saucelabs-demo-java:latest  # Docker Hub repository name


steps:
  # Set the JAVA_HOME environment variable for this run.
  - script: |
      echo "Setting JAVA_HOME_11_X64 environment variable"
      echo "##vso[task.setvariable variable=JAVA_HOME_11_X64]/usr/lib/jvm/java-11-openjdk-amd64"
    displayName: 'Set JAVA_HOME_11_X64'

  # Display the environment variable names (not the values) for debugging purposes.
  - script: |
      if [ -z "$SAUCE_USER" ]; then
        echo "SAUCE_USER is EMPTY!"
      else
        echo "SAUCE_USER is set."
      fi

      if [ -z "$SAUCE_KEY" ]; then
        echo "SAUCE_KEY is EMPTY!"
      else
        echo "SAUCE_KEY is set."
      fi
    displayName: 'Verify SAUCE_USER and SAUCE_KEY'


  # Build and test the Maven project.
  - task: Maven@3
    displayName: 'Maven Build and Test'
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'



  # Building the Docker image
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'

  # Pushing the Docker image to Docker Hub
  - task: Docker@2
    displayName: 'Push Docker Image to Docker Hub'
    inputs:
      containerRegistry: 'Docker'  # Replace with the name of your service connection
      command: 'push'
      repository: '$(saucelabs-demo-java)'
      tags: 'latest'